2019-02-28 22:38:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Индекс "PRIMARY_KEY" уже существует
Index "PRIMARY_KEY" already exists; SQL statement:
create table ORDERS
(
  ID          BIGINT auto_increment,
  ORDERSTATUS VARCHAR
);

create unique index ORDERS_ID_UINDEX
  on ORDERS (ID);

create unique index PRIMARY_KEY
  on ORDERS (ID);
 [42111-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateIndex.update(CreateIndex.java:76)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at ua.rozhkov.project.services.DatabaseService.createTable(DatabaseService.java:104)
	at ua.rozhkov.project.services.DatabaseService.<init>(DatabaseService.java:49)
	at ua.rozhkov.project.services.DatabaseService.getInstance(DatabaseService.java:36)
	at ua.rozhkov.project.App.main(App.java:33)
2019-02-28 22:38:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Индекс "PRIMARY_KEY" уже существует
Index "PRIMARY_KEY" already exists; SQL statement:
create table PRODUCTS
(
  ID    BIGINT auto_increment,
  NAME  VARCHAR(100),
  PRICE DOUBLE
);

create unique index PRODUCTS_ID_UINDEX
  on PRODUCTS (ID);

create unique index PRIMARY_KEY
  on PRODUCTS (ID);
 [42111-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateIndex.update(CreateIndex.java:76)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:36)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at ua.rozhkov.project.services.DatabaseService.createTable(DatabaseService.java:104)
	at ua.rozhkov.project.services.DatabaseService.<init>(DatabaseService.java:54)
	at ua.rozhkov.project.services.DatabaseService.getInstance(DatabaseService.java:36)
	at ua.rozhkov.project.App.main(App.java:33)
2019-03-01 00:24:25 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/JAVA/LS-Project/db/shop.mv.db [1.4.197/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/JAVA/LS-Project/db/shop.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2506)
	at org.h2.mvstore.MVStore.panic(MVStore.java:383)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:364)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at ua.rozhkov.project.services.DatabaseService.getConnection(DatabaseService.java:78)
	at ua.rozhkov.project.services.DatabaseService.dropTables(DatabaseService.java:65)
	at ua.rozhkov.project.services.DatabaseService.<init>(DatabaseService.java:42)
	at ua.rozhkov.project.services.DatabaseService.getInstance(DatabaseService.java:36)
	at ua.rozhkov.project.App.main(App.java:33)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:D:/JAVA/LS-Project/db/shop.mv.db [1.4.197/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/JAVA/LS-Project/db/shop.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 29 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/JAVA/LS-Project/db/shop.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	... 23 more
